return {
  ["error"] = " ",
  ["warn"] = " ",
  ["info"] = " ",
  ["hint"] = " ",
  ["git_add"] = " ",
  ["git_edit"] = " ",
  ["git_del"] = " ",
  ["git_branch"] = "󰘬",
  ["search"] = " ",
  ["dir"] = "󰉋",
  ["dir_empty"] = "󰉋",
  ["dir_empty_open"] = "󰝰",
  ["dir_open"] = "󰝰",
  ["dir_symlink"] = "󰾶",
  ["dir_symlink_open"] = "󰝰",
  ["arrow_open"] = "",
  ["arrow_closed"] = "",
}
